/**
 * Copyright (C) 2011-2015 The XDocReport Team <xdocreport@googlegroups.com>
 *
 * All rights reserved.
 *
 * Permission is hereby granted, free  of charge, to any person obtaining
 * a  copy  of this  software  and  associated  documentation files  (the
 * "Software"), to  deal in  the Software without  restriction, including
 * without limitation  the rights to  use, copy, modify,  merge, publish,
 * distribute,  sublicense, and/or sell  copies of  the Software,  and to
 * permit persons to whom the Software  is furnished to do so, subject to
 * the following conditions:
 *
 * The  above  copyright  notice  and  this permission  notice  shall  be
 * included in all copies or substantial portions of the Software.
 *
 * THE  SOFTWARE IS  PROVIDED  "AS  IS", WITHOUT  WARRANTY  OF ANY  KIND,
 * EXPRESS OR  IMPLIED, INCLUDING  BUT NOT LIMITED  TO THE  WARRANTIES OF
 * MERCHANTABILITY,    FITNESS    FOR    A   PARTICULAR    PURPOSE    AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 * LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE,  ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package fr.opensagres.xdocreport.remoting.resources.services.jaxws;

import java.net.URL;

import javax.xml.namespace.QName;

import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-06-11T23:09:18.779+02:00
 * Generated source version: 2.6.1
 * 
 */
@WebServiceClient(name = "JAXWSResourcesServiceService", 
                  wsdlLocation = "JAXWSResourcesServiceService.wsdl",
                  targetNamespace = "http://ws.services.resources.remoting.xdocreport.opensagres.fr/") 
public class JAXWSResourcesServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.services.resources.remoting.xdocreport.opensagres.fr/", "JAXWSResourcesServiceService");
    public final static QName JAXWSResourcesServicePort = new QName("http://ws.services.resources.remoting.xdocreport.opensagres.fr/", "JAXWSResourcesServicePort");
    static {
        URL url = JAXWSResourcesServiceService.class.getResource("JAXWSResourcesServiceService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(JAXWSResourcesServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "JAXWSResourcesServiceService.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public JAXWSResourcesServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public JAXWSResourcesServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JAXWSResourcesServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns JAXWSResourcesService
     */
    @WebEndpoint(name = "JAXWSResourcesServicePort")
    public JAXWSResourcesService getJAXWSResourcesServicePort() {
        return super.getPort(JAXWSResourcesServicePort, JAXWSResourcesService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JAXWSResourcesService
     */
    @WebEndpoint(name = "JAXWSResourcesServicePort")
    public JAXWSResourcesService getJAXWSResourcesServicePort(WebServiceFeature... features) {
        return super.getPort(JAXWSResourcesServicePort, JAXWSResourcesService.class, features);
    }

}
