package fr.opensagres.xdocreport.remoting.resources.services.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import fr.opensagres.xdocreport.remoting.resources.domain.BinaryData;
import fr.opensagres.xdocreport.remoting.resources.domain.Filter;
import fr.opensagres.xdocreport.remoting.resources.domain.Resource;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-06-11T00:59:04.745+02:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://ws.services.resources.remoting.xdocreport.opensagres.fr/", name = "JAXWSResourcesService")
public interface JAXWSResourcesService {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebMethod
    public void upload(
        @WebParam(partName = "content", name = "content", targetNamespace = "")
        BinaryData content
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "resource", targetNamespace = "", partName = "resource")
    @WebMethod(action="getRoot")
    public Resource getRoot();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "downloadMultiple", targetNamespace = "http://ws.services.resources.remoting.xdocreport.opensagres.fr/", className = "fr.opensagres.xdocreport.remoting.resources.services.ws.DownloadMultiple")
    @WebMethod
    @ResponseWrapper(localName = "downloadMultipleResponse", targetNamespace = "http://ws.services.resources.remoting.xdocreport.opensagres.fr/", className = "fr.opensagres.xdocreport.remoting.resources.services.ws.DownloadMultipleResponse")
    public java.util.List<BinaryData> downloadMultiple(
        @WebParam(name = "resourceIds", targetNamespace = "")
        java.util.List<java.lang.String> resourceIds
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "parameters", targetNamespace = "", partName = "parameters")
    @WebMethod(action="getName")
    public java.lang.String getName();

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "parameters", targetNamespace = "", partName = "parameters")
    @WebMethod
    public BinaryData download(
        @WebParam(partName = "resourceId", name = "resourceId", targetNamespace = "")
        java.lang.String resourceId
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "resource", targetNamespace = "", partName = "resource")
    @WebMethod
    public Resource getRootWithFilter(
        @WebParam(partName = "filter", name = "filter", targetNamespace = "")
        Filter filter
    );
}
