package fr.opensagres.xdocreport.remoting.resources.services.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import fr.opensagres.xdocreport.remoting.resources.services.ResourcesService;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-06-11T23:09:18.718+02:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://ws.services.resources.remoting.xdocreport.opensagres.fr/", name = "JAXWSResourcesService")
@XmlSeeAlso({fr.opensagres.xdocreport.remoting.resources.domain.ObjectFactory.class})
public interface JAXWSResourcesService extends ResourcesService {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebMethod
    public void upload(
        @WebParam(partName = "content", name = "content", targetNamespace = "http://domain.resources.remoting.xdocreport.opensagres.fr/")
        fr.opensagres.xdocreport.remoting.resources.domain.BinaryData content
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "resource", targetNamespace = "http://domain.resources.remoting.xdocreport.opensagres.fr/", partName = "resource")
    @WebMethod(action = "getRoot")
    public fr.opensagres.xdocreport.remoting.resources.domain.Resource getRoot();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "downloadMultiple", targetNamespace = "http://domain.resources.remoting.xdocreport.opensagres.fr/", className = "fr.opensagres.xdocreport.remoting.resources.domain.DownloadMultiple")
    @WebMethod
    @ResponseWrapper(localName = "downloadMultipleResponse", targetNamespace = "http://domain.resources.remoting.xdocreport.opensagres.fr/", className = "fr.opensagres.xdocreport.remoting.resources.domain.DownloadMultipleResponse")
    public java.util.List<fr.opensagres.xdocreport.remoting.resources.domain.BinaryData> downloadMultiple(
        @WebParam(name = "resourceIds", targetNamespace = "")
        java.util.List<java.lang.String> resourceIds
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "parameters", targetNamespace = "http://domain.resources.remoting.xdocreport.opensagres.fr/", partName = "parameters")
    @WebMethod(action = "getName")
    public java.lang.String getName();

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "parameters", targetNamespace = "", partName = "parameters")
    @WebMethod
    public fr.opensagres.xdocreport.remoting.resources.domain.BinaryData download(
        @WebParam(partName = "resourceId", name = "resourceId", targetNamespace = "http://domain.resources.remoting.xdocreport.opensagres.fr/")
        java.lang.String resourceId
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "resource", targetNamespace = "http://domain.resources.remoting.xdocreport.opensagres.fr/", partName = "resource")
    @WebMethod
    public fr.opensagres.xdocreport.remoting.resources.domain.Resource getRootWithFilter(
        @WebParam(partName = "filter", name = "filter", targetNamespace = "http://domain.resources.remoting.xdocreport.opensagres.fr/")
        fr.opensagres.xdocreport.remoting.resources.domain.Filter filter
    );
}
