//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.06.09 at 04:23:24 PM CEST
//


package fr.opensagres.xdocreport.remoting.resources.domain;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the fr.opensagres.xdocreport.remoting.resources.services package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Resource_QNAME = new QName("http://domain.resources.remoting.xdocreport.opensagres.fr/", "resource");
    private final static QName _BinaryData_QNAME = new QName("http://domain.resources.remoting.xdocreport.opensagres.fr/", "binaryData");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fr.opensagres.xdocreport.remoting.resources.domain
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Filter }
     *
     */
    public Filter createFilter() {
        return new Filter();
    }

    /**
     * Create an instance of {@link BinaryData }
     *
     */
    public BinaryData createBinaryData() {
        return new BinaryData();
    }

    /**
     * Create an instance of {@link PropertyRepresentation }
     *
     */
    public PropertyRepresentation createPropertyRepresentation() {
        return new PropertyRepresentation();
    }

    /**
     * Create an instance of {@link Resource }
     *
     */
    public Resource createResource() {
        return new Resource();
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Resource }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://domain.resources.remoting.xdocreport.opensagres.fr/", name = "resource")
    public JAXBElement<Resource> createResource(Resource value) {
        return new JAXBElement<Resource>(_Resource_QNAME, Resource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BinaryData }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://domain.resources.remoting.xdocreport.opensagres.fr/", name = "binaryData")
    public JAXBElement<BinaryData> createBinaryData(BinaryData value) {
        return new JAXBElement<BinaryData>(_BinaryData_QNAME, BinaryData.class, null, value);
    }



}
