
package fr.opensagres.xdocreport.remoting.resources.services.ws.client.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.0
 * Wed Mar 07 07:57:58 CET 2012
 * Generated source version: 2.4.0
 */

@XmlRootElement(name = "getNameResponse", namespace = "http://services.resources.remoting.xdocreport.opensagres.fr/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getNameResponse", namespace = "http://services.resources.remoting.xdocreport.opensagres.fr/")

public class GetNameResponse {

    @XmlElement(name = "return", namespace = "http://services.resources.remoting.xdocreport.opensagres.fr/")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

