
package fr.opensagres.xdocreport.remoting.resources.services.ws.client.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.0
 * Wed Mar 07 07:57:58 CET 2012
 * Generated source version: 2.4.0
 */

@XmlRootElement(name = "getRoot1", namespace = "http://services.resources.remoting.xdocreport.opensagres.fr/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getRoot1", namespace = "http://services.resources.remoting.xdocreport.opensagres.fr/")

public class GetRoot1 {

    @XmlElement(name = "arg0")
    private fr.opensagres.xdocreport.remoting.resources.domain.Filter arg0;

    public fr.opensagres.xdocreport.remoting.resources.domain.Filter getArg0() {
        return this.arg0;
    }

    public void setArg0(fr.opensagres.xdocreport.remoting.resources.domain.Filter newArg0)  {
        this.arg0 = newArg0;
    }

}

